services:
  web:
    image: ppk4/simple
    container_name: simple-container
    environment:
      - APP_COLOR=BLUE
    deploy:
      replicas: 3
      restart_policy: 
        condition: on-failure
      update_config: 
        parallelism: 2
        delay: 10s
